/**
 * Scans public/signs/ and writes lib/sign-images.ts, mapping sign id -> public path.
 *
 * Runs automatically before `npm run dev` and `npm run build`. Run it by hand with
 * `npm run signs` if you add an image while the dev server is already running.
 */
import { existsSync, mkdirSync, readdirSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { SIGNS } from '../lib/signs.ts'

const DIR = path.join('public', 'signs')
const OUT = path.join('lib', 'sign-images.ts')
const ALLOWED = ['.png', '.jpg', '.jpeg', '.webp', '.svg', '.gif']

if (!existsSync(DIR)) mkdirSync(DIR, { recursive: true })

const known = new Set(SIGNS.map((s) => s.id))
const found = new Map<string, string>()
const unknown: string[] = []

for (const file of readdirSync(DIR)) {
  const ext = path.extname(file).toLowerCase()
  if (!ALLOWED.includes(ext)) continue
  const id = path.basename(file, ext)
  if (!known.has(id)) {
    unknown.push(file)
    continue
  }
  found.set(id, `/signs/${file}`)
}

const entries = [...found.entries()].sort(([a], [b]) => a.localeCompare(b))

writeFileSync(
  OUT,
  `// GENERATED by scripts/build-sign-manifest.mts — do not edit.
// Drop an image into public/signs/ named after a sign id to override its drawing.

export const SIGN_IMAGES: Record<string, string> = {
${entries.map(([id, src]) => `  ${JSON.stringify(id)}: ${JSON.stringify(src)},`).join('\n')}
}
`,
  'utf8',
)

console.log(`sign images: ${entries.length} of ${known.size} supplied`)
for (const [id, src] of entries) console.log(`  ${id} -> ${src}`)
if (unknown.length) {
  console.log(`\nignored (filename doesn't match any sign id):`)
  for (const f of unknown) console.log(`  ${f}`)
  console.log(`\nvalid ids: ${[...known].join(', ')}`)
}
